### ISSUE TITLE
Source file is not valid UTF-8.

### ISSUE THREAD

**Issue by holyCoco** [zweigraf/face-landmarking-ios#1]
When i drag the libdlib.a in my Xcode,the error "Source file is not valid UTF-8" appeared,and could you tell me how to solve？

**Comment by zweigraf** [comment]
Could you tell me in more detail what you are trying to accomplish? 

You do not need to drag the libdlib.a anywhere if you just want to run this project as is.

The error sounds like you dragged the libdlib.a into the "Compile Sources" section of the project. This is not correct.

**Comment by holyCoco** [comment]
Is my carelessness, I solved the problem, thank you.

**Comment by zweigraf** [comment]
Great to hear :) Have a great day.
