### ISSUE TITLE
Issue with project's compiling

### ISSUE THREAD

**Issue by WhiteRaby** [zweigraf/face-landmarking-ios#2]
Hi, Luis Reisewitz.
First of all thank you for the excellent work, your app works very well.
My issue is that When i tried to reproduce your project I had slow fps on my iPhone (when I compiled Your project it worked with good fps)

Below what I did: 
1) Created new project 
2) Copied all source files (both DlibWrapper, ViewController, SessionHandler, Bridging-Header, Storyboard file)
3) Created lib directory and copied from your directory dlib source code, libdlib.a, shape_predictor_68_face_landmarks
4) In Build Settings I tuned next items:
- Header search path and Library search path similar with your settings
- Preprocessor macros were set as well.

5) In Build Phases I added Accelerate.framework and libdlib.a to Link Binary..
6) To Copy bundle resources was added shape_predictor_68_face_landmark

What's I forget?
P.S. here's my rap, just in case: github.com/WhiteRaby/Dlib

**Comment by zweigraf** [comment]
I have not had time to look at your project yet, but:

Please check your schemes and make sure that you are compiling the app in Release mode, not Debug mode.

**Comment by WhiteRaby** [comment]
I changed this mode to the release and it solved my issue! Many thanks, Luis.

**Comment by zweigraf** [comment]
Great to hear that that worked :) Happy to have helped.
