### ISSUE TITLE
How to do this face landmarking with image

### ISSUE THREAD

**Issue by WaqarKhalid** [zweigraf/face-landmarking-ios#21]
I want to use still image from my phone gallery for landmarking.How can I do that?

**Comment by zweigraf** [comment]
Check #11 for more information. Basically you need to get the pixel buffer of the image and then run that to a modified version of this app. Please use the other issue for further discussion.

**Comment by shaileshh** [comment]
@zweigraf i managed to convert this swift project to objective c, should i upload it?
