### ISSUE TITLE
'vector' file not found

### ISSUE THREAD

**Issue by aguusvazquez** [zweigraf/face-landmarking-ios#29]
Hi, first of all, thanks a lot for the library! It's great!!
I'm having this issue everytime, and I don't know how to fix it:

ios/lib/dlib/image_processing/scan_image.h:6:10: 'vector' file not found

This happens when I include this line in the .m file: 

#include <dlib/image_processing.h>

Anyone knows why this is happening?

Thank you very much!!

Agustin

**Comment by lawliet0823** [comment]
.m file is for Objective-C
.mm file is for Objective-C、C/C++
You should try to change your filename extension.

**Comment by aguusvazquez** [comment]
@lawliet0823 Thanks man!! Now it's compiling well
